# Agent OS Configuration

# Refer to the official Agent OS documentation at:
# https://ChenReuven.com/cyberark-ai-spec-os

agent_os_version: 1.4.1

agents:
  claude_code:
    enabled: false
  cursor:
    enabled: false

project_types:
  default:
    instructions: ~/.cyberark-spec-os/instructions
    standards: ~/.cyberark-spec-os/standards

  # type_a:
  #   instructions: ~/.cyberark-spec-os/project_types/type_a/instructions
  #   standards: ~/.cyberark-spec-os/project_types/type_a/standards

  # type_b:
  #   instructions: ~/.cyberark-spec-os/project_types/type_b/instructions
  #   standards: ~/.cyberark-spec-os/project_types/type_b/standards

default_project_type: default
