# Agent OS Configuration

# Refer to the official Agent OS documentation at:
# https://ChenReuven.com/cyberark-ai-spec-os

agent_os_version: 1.4.1

agents:
  claude_code:
    enabled: false
  cursor:
    enabled: false
  github_copilot:
    enabled: true

project_types:
  default:
    instructions: ~/.cyberark-spec-os/instructions
    standards: ~/.cyberark-spec-os/standards

  python:
    instructions: ~/.agent-os/instructions
    standards: ~/.agent-os/project_types/python/standards

  golang:
    instructions: ~/.agent-os/instructions
    standards: ~/.agent-os/project_types/golang/standards


default_project_type: default
